// Generated by scripts/build-manufacturer-logos.js (npm run
// build-manufacturer-logos), base64 data-URI per manufacturer, keyed by the
// same canonical slug src/main/manufacturerLogos.ts resolves a driver's
// CarScreenName to. Re-run the script to refresh (e.g. after a new car
// brand shows up), the raw source lives externally (avto-dev/vehicle-logotypes),
// not in this repo.
import data from './data.json'

const LOGOS: Record<string, string> = data

export function manufacturerLogoDataUri(key: string | null): string | null {
  if (!key) return null
  return LOGOS[key] ?? null
}
